[features]
seeds = false
skip-lint = false

[programs.localnet]
lol_tournament = "54N5nsEJgPWf4ghPn6teZrseTxLo7wr1vLBMLGhruVgx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "yarn run ts-node client/*.ts"
